services:
- type: web
  name: fastapi-service
  env: python
  buildCommand: pip install -r src/requirements.txt
  startCommand: uvicorn src.main:app --host 0.0.0.0 --port 80
  envVars:
  - key: PYTHONUNBUFFERED
    value: 'true'
  - key: ENVIRONMENT
    value: production
  healthCheckPath: /
  routes:
  - type: rewrite
    source: /.*
    destination: /